apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: madrent/ambulance-ufe
  newName: madrent/ambulance-ufe
  newTag: 1.3.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: madrent/ambulance-wl-webapi
  newName: madrent/ambulance-wl-webapi
  newTag: 1.2.0

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: lbmjm-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  lbmjm-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1