apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbmjm-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: lbmjm-ambulance-wl-webapi-container
          env:
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.wac-hospital:4317
            - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_SAMPLER
              # see https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_traces_sampler
              value: "parentbased_always_on"
        - name: openapi-ui
          env:
            - name: URL
              value: /lbmjm-openapi
            - name: BASE_URL
              value: /lbmjm-openapi-ui