apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: madrent/ambulance-ufe
  newName: madrent/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240527.0723 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: madrent/ambulance-wl-webapi
  newName: madrent/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240526.1037 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
